name: Release to PyPI

on:
  release:
    type: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: JRubics/poetry-publish@v1.6
      with:
        python_version: '3.8.5'
        pypi_token: ${{ secrets.PYPI_TOKEN }}
